# Generated by Django 3.1.1 on 2021-03-06 08:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title for question')),
                ('content', models.TextField(blank=True, default='', verbose_name='more information about question')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('votes', models.IntegerField(verbose_name='number of votes cast')),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
