# Generated by Django 3.1.1 on 2021-03-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='number of votes cast'),
        ),
    ]
