# Generated by Django 3.1.1 on 2021-03-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210310_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content_markdown',
            field=models.TextField(default='', null=True),
        ),
    ]
