# Generated by Django 3.1.1 on 2021-03-14 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20210311_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.answer')),
                ('users_downvoted', models.ManyToManyField(blank=True, related_name='answer_downvotes', to=settings.AUTH_USER_MODEL)),
                ('users_upvoted', models.ManyToManyField(blank=True, related_name='answer_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
